---
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: hotel
    static_configs:
      - targets: ["host.docker.internal:5745"]
  - job_name: booking
    static_configs:
      - targets: ["host.docker.internal:5746"]